apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: daprbus
spec:
  type: pubsub.azure.servicebus
  version: v1
  metadata:
  - name: connectionString
    value: Endpoint=sb://{namespace}.servicebus.windows.net/;SharedAccessKeyName={KEYNAME};SharedAccessKey={KEYVALUE};EntityPath={TOPIC}